networks:
  app-network:
    driver: bridge

services:
  # mysql:
  #   image: 'mysql/mysql-server:8.0'
  #   ports:
  #     - '${FORWARD_DB_PORT:-3307}:3306'
  #   environment:
  #     MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
  #     MYSQL_ROOT_HOST: '${DB_HOST}'
  #     MYSQL_DATABASE: '${DB_DATABASE}'
  #     MYSQL_USER: '${DB_USERNAME}'
  #     MYSQL_PASSWORD: '${DB_PASSWORD}'
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 1
  #   volumes:
  #     - 'sail-mysql:/var/lib/mysql'
  #     - './backend/docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
  #   networks:
  #     - app-network
  #   healthcheck:
  #     test:
  #       - CMD
  #       - mysqladmin
  #       - ping
  #       - '-p${DB_PASSWORD}'
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6378}:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - app-network
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/var/www/html/backend
      - ./backend/vendor:/var/www/html/backend/vendor
    # command: >
    #   sh -c "
    #     php artisan migrate &&
    #     php artisan serve --host=0.0.0.0 --port=8000
    #   "

    command: >
      sh -c "
        php artisan migrate
      "
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - app-network
    env_file:
      - .env
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/backend.example.com.conf:/etc/nginx/conf.d/backend.example.com.conf
      - ./backend/public:/var/www/html/backend/public
    depends_on:
      - backend
    ports:
      - "81:81"
    networks:
      - app-network

  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: 
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks: 
      - app-network

volumes:
  sail-redis:
  sail-mysql:
  postgres_data:
  rabbitmq_data: